### ISSUE TITLE
Can not load pretrain w2v

### ISSUE THREAD

**Issue by Hieunv1996** [vietnlp/etnlp#2]
Em chào anh ạ, em có thử download pretrain word embedding [**Link 6**](https://drive.google.com/open?id=1Cr-3ST4aac8O807tDFEYsohDyXWUJVMV) về thì không mở lên được. Trong readme có nói model này là kết hợp của nhiều model, vậy làm sao để em dùng nó ạ?
```
>>> from gensim.models import KeyedVectors
>>> en_model = KeyedVectors.load_word2vec_format('MULTI_W_F_B_E.vec')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lap60313/.local/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 1476, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/lap60313/.local/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 344, in _load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/home/lap60313/.local/lib/python3.6/site-packages/gensim/models/utils_any2vec.py", line 344, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: '!'
```
Nhân tiện em muốn góp ý là anh cung cấp `ndim` bên cạnh để mọi người đỡ phải check thông tin ạ :D

**Comment by sonvx** [comment]
Nhân tiện em muốn góp ý là anh cung cấp ndim bên cạnh để mọi người đỡ phải check thông tin ạ :D
-> a update rồi em nhé.

`MULTI_W_F_B_E.vec`: em download lại là ok nhé, a đã update.
