### ISSUE TITLE
Issue because TensorFlow modules are deprecated

### ISSUE THREAD

**Issue by dataislife** [vietnlp/etnlp#7]
Hi, 

I am facing the following issue when running: 

```
sh 03.run_etnlp_visualizer_inter.sh 
```

```
Traceback (most recent call last):
  File "./etnlp_api.py", line 91, in <module>
    embedding_visualizer.visualize_multiple_embeddings(input_embedding_files_str, port)
  File ".../Visualization/etnlp/src/codes/api/embedding_visualizer.py", line 223, in visualize_multiple_embeddings
    visualize_multiple_embeddings_all_in_one(paths_of_emb_models, port)
  File ".../Visualization/etnlp/src/codes/api/embedding_visualizer.py", line 206, in visualize_multiple_embeddings_all_in_one
    convert_multiple_emb_models_2_tf(embedding_name_arr, w2v_embedding_model_arr, tf_data_folder, starting_port)
  File "..../Visualization/etnlp/src/codes/api/embedding_visualizer.py", line 84, in convert_multiple_emb_models_2_tf
    tb_tool.run(all_emb_name, port)
  File "...../Visualization/etnlp/src/codes/api/embedding_visualizer.py", line 27, in run
    tb = program.TensorBoard(default.get_plugins(), default.get_assets_zip_provider())
AttributeError: module 'tensorboard.default' has no attribute 'get_assets_zip_provider'
```

So the line in python that is a problem is in def run(self, emb_name, port) from  src/codes/api/embedding_visualizer.py: 

```python 
# Start tensorboard server
tb = program.TensorBoard(default.get_plugins(), default.get_assets_zip_provider())        tb.configure(argv=[None, '--logdir', self.dir_path, '--port', str(port)])
```
There were also a lot of warnings due to the modules used in TensorFlow now deprecated. It would be great to update the source code with this respect. 

**Any idea regarding the mentioned issue is welcome! :)**

Great job! 👍

**Comment by sonvx** [comment]
@dataislife thanks for your request. More about the issue, please let me know what TF version you are using. Normally, it will not be much different if you are using  TF < 2.0.
