### ISSUE TITLE
Can't run evaluator example

### ISSUE THREAD

**Issue by Avi197** [vietnlp/etnlp#8]
When i try to run the evaluator example, i got some errors

`Traceback (most recent call last):
  File "test3_etnlp_evaluator.py", line 11, in <module>
    embedding_evaluator.evaluator_api(INPUT_FILES, ANALOGY_FILE, OUT_FILE)
  File "/home/hosson/enviroment/general_venv/lib/python3.6/site-packages/ETNLP-0.1.3-py3.6.egg/api/embedding_evaluator.py", line 308, in evaluator_api
    output_file=output)
  File "/home/hosson/enviroment/general_venv/lib/python3.6/site-packages/ETNLP-0.1.3-py3.6.egg/utils/emb_utils.py", line 202, in eval_word_analogy_4_all_embeddings
    map_at_10, map_arr, result_str = eval_word_analogies(word_analogies_file, word_embedding, embedding_name)
  File "/home/hosson/enviroment/general_venv/lib/python3.6/site-packages/ETNLP-0.1.3-py3.6.egg/utils/emb_utils.py", line 302, in eval_word_analogies
    word_right2, words)
  File "/home/hosson/enviroment/general_venv/lib/python3.6/site-packages/ETNLP-0.1.3-py3.6.egg/utils/emb_utils.py", line 99, in closest_analogies_vectors
    word_right2.vector)
  File "/home/hosson/enviroment/general_venv/lib/python3.6/site-packages/ETNLP-0.1.3-py3.6.egg/utils/vectors.py", line 48, in add
    assert v1.shape == v2.shape
AttributeError: 'NoneType' object has no attribute 'shape'
`

**Comment by lijie-star** [comment]
I got this error too. How did you solve it?
